# Error messages for ignite.sh. Sourced — not run directly.
ERR_BN_I="Invalid key size (use 2048, 3072 or 4096)"
ERR_CD_I="Invalid certificate duration (1-3650 days)"
ERR_CFG_FNF="Configuration file not found"
ERR_CFG_FNS="Configuration file not set"
ERR_CRT_FNF="CRT file not found"
ERR_CRT_FNS="CRT file not set"
ERR_CRT_NC="Not a PEM certificate - expected a .crt containing 'BEGIN CERTIFICATE' (a .cfg/.csr/.key won't work)"
ERR_DN_I="Invalid domain"
ERR_DN_NS="Domain not set"
ERR_EE="Execution error"
ERR_FEC="Failed to execute command"
ERR_KEY_FNF="KEY file not found"
ERR_KEY_FNS="KEY file not set"
ERR_KEY_NK="Not a PEM private key - expected a .key containing 'PRIVATE KEY'"
ERR_OPENSSL="openssl not found - install it and retry"
ERR_SS_I="Invalid subject string"
ERR_SS_MI="Subject string missing required fields (/C=, /O=, /CN=)"
ERR_SSF_I="Invalid self-signed flag (use 0 or 1)"
ERR_SSF_NS="Self-signed flag not set"
ERR_SUBJ_SRC="Provide a subject string with -i, or a config file with -f"
ERR_TPLF_I="Invalid template flag (use 0 or 1)"
ERR_TPLF_NS="Template flag not set"
ERR_UO="Unidentified option"
ERR_UP="Unidentified protocol"
